mod_version=1.0.0
maven_group=com.craftstats
archives_base_name=craftstats

minecraft_version=1.21.10
java_version=21

architectury_version=18.0.8
architectury_fabric_version=18.0.8
architectury_neoforge_version=18.0.8
architectury_loom_version=1.12-SNAPSHOT
architectury_plugin_version=3.4.161

fabric_loader_version=0.16.14
fabric_api_version=0.138.4+1.21.10

cloth_config_version=20.0.152
modmenu_version=16.0.0

neoforge_version=21.10.10
