mod_version=1.0.0
maven_group=com.craftstats
archives_base_name=craftstats

minecraft_version=1.21.7
java_version=21

architectury_version=17.0.6
architectury_fabric_version=17.0.6
architectury_neoforge_version=17.0.6
architectury_loom_version=1.10-SNAPSHOT
architectury_plugin_version=3.4.161

fabric_loader_version=0.16.14
fabric_api_version=0.129.0+1.21.7

cloth_config_version=19.0.149
modmenu_version=15.0.0

neoforge_version=21.7.10
