architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/craftstats.accesswidener")
}

dependencies {
    // Only for @Environment annotations and mixin dependencies; nothing Fabric-specific is used.
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "dev.architectury:architectury:${rootProject.architectury_version}"
}
